openapi: '3.0.3'

info:
  description: JuicyEats Backend
  version: 0.1.0
  title: JuicyEats Backend

servers:
  - url: http://localhost:3500/v0

paths:
  /listings:
    get:
      description: GET all listings
      parameters:
        - in: query
          name: search
          description: Search keywords
          required: false
          schema:
            type: string
            pattern: '^(?:\S+ )*(?:\S+)$'
      responses:
        200:
          description: Successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListingList'
        400:
          description: Invalid search
        404:
          description: No items found
  
  /listing/{id}:
    get:
      description: GET listing by id
      parameters:
        - name: id
          in: path
          description: Listing id
          required: true
          schema:
            type: string
      responses:
        200:
          description: Successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Listing'
        404:
          description: Listing not found
    patch:
      description: Find listing by id and update
      parameters:
        - name: id
          in: path
          description: Listing id
          required: true
          schema:
            type: string
      requestBody:
        description: Listing details
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateListing'
      responses:
        200:
          description: Listing successfully updated
        400:
          description: Invalid listing update
        404:
          description: Listing not found
    delete:
      description: Delete listing by id
      parameters:
        - name: id
          in: path
          description: Listing id
          required: true
          schema:
            type: string
      responses:
        200:
          description: Listing successfully deleted
        400:
          description: Invalid listing id
        404:
          description: Listing not found
  
  /listing:
    post:
      description: Create new listing
      requestBody:
        description: Listing details
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewListing'
      responses:
        201:
          description: Listing created
        400:
          description: Invalid listing


components:
  schemas:
    Listing:
      type: object
      properties:
        _id:
          type: object
        title:
          type: string
        price:
          type: number
          format: float
        available:
          type: boolean
      required:
        - _id
        - title
        - price
        - available
      additionalProperties: false

    ListingList:
      type: array
      items:
        $ref: '#/components/schemas/Listing'

    NewListing:
      type: object
      properties:
        title:
          type: string
        price:
          type: number
          format: float
        available:
          type: boolean
      required:
        - title
        - price
        - available
      additionalProperties: false

    UpdateListing:
      type: object
      properties:
        title:
          type: string
        price:
          type: number
          format: float
        available:
          type: boolean
      additionalProperties: false